version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: container-project-course-udemy
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      #- /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: db-container-project-course-udemy
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #postgres_data => esse volume esta na minha maquina o host
    #/var/lib/postgresql/data => Este esta no container
volumes:
  postgres_data:
